name: Code Quality

on:
  # Only run on pull requests to avoid duplicate runs
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/*.md'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format || echo "dotnet-format installation failed but continuing workflow"
      continue-on-error: true
    
    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: true
    
    - name: Check code format
      run: dotnet format --verify-no-changes --verbosity diagnostic || echo "Format check failed but continuing workflow"
      continue-on-error: true
    
    - name: Check for StyleCop issues
      run: |
        # Check if StyleCop is already referenced in the projects
        echo "Checking for StyleCop issues in existing code"
        dotnet build --no-restore || echo "Build for StyleCop check failed but continuing workflow"
      continue-on-error: true
