name: Documentation Generation

on:
  # Run on push to main (after PR is merged)
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - '**/*.cs'  # For XML comments in code
  # Run on PRs that modify documentation
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - '**/*.md'
      - '**/*.cs'  # For XML comments in code
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install DocFX
      run: dotnet tool install -g docfx || echo "DocFX installation failed but continuing workflow"
      continue-on-error: true
    
    - name: Create DocFX project
      run: |
        mkdir -p docfx
        cd docfx
        docfx init -q || echo "DocFX init failed but continuing workflow"
      continue-on-error: true
    
    - name: Update DocFX configuration
      run: |
        if [ -f "docfx/docfx.json" ]; then
          sed -i 's/"src\/\*\*\/\*.csproj"/"src\/WendoverHOA.Domain\/WendoverHOA.Domain.csproj", "src\/WendoverHOA.Application\/WendoverHOA.Application.csproj", "src\/WendoverHOA.Infrastructure\/WendoverHOA.Infrastructure.csproj", "src\/WendoverHOA.Web\/WendoverHOA.Web.csproj"/g' docfx/docfx.json
        else
          echo "docfx.json not found, skipping configuration update"
        fi
      continue-on-error: true
    
    - name: Build documentation
      run: |
        if [ -d "docfx" ]; then
          cd docfx
          docfx build || echo "DocFX build failed but continuing workflow"
        else
          echo "DocFX directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Deploy documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref == 'refs/heads/main'
      with:
        folder: ./docfx/_site
        branch: gh-pages
        clean: true
      continue-on-error: true
